#!/bin/bash

if [ $# != 1 ]; then
    echo "Pick an assignment to test"
    exit 1
fi

cargo build

if [ $? != 0 ]; then
    echo "Failed to compile!"
    exit 1
fi

for f in `find $1/1_parser -type f | cut -d'.' -f1 | sort | uniq`; do
    echo $f.jsish
    cargo run $f.jsish 2> /dev/null | diff $f.correct -
done

for f in `find $1/2_3_ast_echo -type f | cut -d'.' -f1 | sort | uniq`; do
    echo $f.jsish
    cargo run -- $f.jsish --print 2> /dev/null | diff $f.correct -
done

for f in `find $1/4_eval -type f | cut -d'.' -f1 | sort | uniq`; do
    echo $f.jsish
    cargo run $f.jsish 2> /dev/null | diff $f.correct -
done

for f in `find $1/4_type_error -type f | cut -d'.' -f1 | sort | uniq`; do
    echo $f.jsish
    cargo run $f.jsish 2> /dev/null | diff $f.correct -
done

for f in `find $1/5_gc -type f | cut -d'.' -f1 | sort | uniq`; do
    echo $f.jsish
    cargo run $f.jsish 2> /dev/null | diff $f.correct -
done
