#!/bin/bash

for hw_dir in "$@"; do
    for f in `find $hw_dir/1_parser -type f | cut -d'.' -f1 | sort | uniq`; do
        echo $f.jsish
        cargo run $f.jsish 2> /dev/null | diff $f.correct -
        if [ $? != 0 ]; then
            exit 1
        fi
    done

    for f in `find $hw_dir/2_3_ast_echo -type f | cut -d'.' -f1 | sort | uniq`; do
        echo $f.jsish
        cargo run -- $f.jsish --print 2> /dev/null | diff $f.correct -
        if [ $? != 0 ]; then
            exit 1
        fi
    done

    for f in `find $hw_dir/4_eval -type f | cut -d'.' -f1 | sort | uniq`; do
        echo $f.jsish
        cargo run $f.jsish 2> /dev/null | diff $f.correct -
        if [ $? != 0 ]; then
            exit 1
        fi
    done

    for f in `find $hw_dir/4_type_error -type f | cut -d'.' -f1 | sort | uniq`; do
        echo $f.jsish
        cargo run $f.jsish 2> /dev/null | diff $f.correct -
        if [ $? != 0 ]; then
            exit 1
        fi
    done

    if [ -d $hw_dir/5_gc ]; then
        for f in `find $hw_dir/5_gc -type f | cut -d'.' -f1 | sort | uniq`; do
            echo $f.jsish
            cargo run $f.jsish 2> /dev/null | diff $f.correct -
            if [ $? != 0 ]; then
                exit 1
            fi
        done
    fi
done
