#!/bin/bash

for hw_dir in "$@"; do
    for f in `find $hw_dir/1_parser -type f | cut -d'.' -f1 | sort | uniq`; do
        rm tmp.out tmp.err
        echo $f.jsish
        cargo run -q $f.jsish > tmp.out 2> tmp.err; 
        cat tmp.err tmp.out | diff $f.correct -
        RES=$?
        rm tmp.out tmp.err
        if [ RES != 0 ]; then
            exit 1
        fi
    done

    for f in `find $hw_dir/2_3_ast_echo -type f | cut -d'.' -f1 | sort | uniq`; do
        echo $f.jsish
        cargo run -q -- --print $f.jsish > tmp.out 2> tmp.err; 
        cat tmp.err tmp.out | diff $f.correct -
        RES=$?
        rm tmp.out tmp.err
        if [ RES != 0 ]; then
            exit 1
        fi
    done

    for f in `find $hw_dir/4_eval -type f | cut -d'.' -f1 | sort | uniq`; do
        echo $f.jsish
        cargo run -q $f.jsish > tmp.out 2> tmp.err; 
        cat tmp.err tmp.out | diff $f.correct -
        RES=$?
        rm tmp.out tmp.err
        if [ RES != 0 ]; then
            exit 1
        fi
    done

    for f in `find $hw_dir/4_type_error -type f | cut -d'.' -f1 | sort | uniq`; do
        echo $f.jsish
        cargo run -q $f.jsish > tmp.out 2> tmp.err; 
        cat tmp.err tmp.out | diff $f.correct -
        RES=$?
        rm tmp.out tmp.err
        if [ RES != 0 ]; then
            exit 1
        fi
    done

    if [ -d $hw_dir/5_gc ]; then
        for f in `find $hw_dir/5_gc -type f | cut -d'.' -f1 | sort | uniq`; do
            echo $f.jsish
            cargo run -q $f.jsish > tmp.out 2> tmp.err; 
            cat tmp.err tmp.out | diff $f.correct -
            RES=$?
            rm tmp.out tmp.err
            if [ RES != 0 ]; then
                exit 1
            fi
        done
    fi
done
